name: test
on:
  push:
    branches:
      - "**"
  pull_request: {}
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack:0.14.2
        ports:
          - 4566:4566
        env:
          SERVICES: sts

    steps:
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: checkout
        uses: actions/checkout@v2

      - name: Install GolangCI-Lint
        run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.46.1

      - name: Run GolangCI-Lint
        run: golangci-lint run --config .golangci.yml

      - name: test
        run: go test -v ./...
        env:
          AWS_ACCESS_KEY_ID: dummy
          AWS_SECRET_ACCESS_KEY: dummy
